# Generated by Django 5.1 on 2024-08-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='package_details',
            new_name='Description',
        ),
    ]
#query params , params , swaggers, django forms
